export const EVENTS = [
  {
    id: 1,
    title: "Tech Talk: Future of AI",
    type: "Workshop",
    date: "24 May",
    time: "4:00 PM",
    location: "Seminar Hall, Techno Main",
    attendees: 124,
    image: "/images/friend/event1.png",
  },
  {
    id: 2,
    title: "Hackathon 2025",
    type: "Hackathon",
    date: "31 May",
    time: "9:00 AM",
    location: "Innovation Lab",
    attendees: 186,
    image: "/images/friend/event1.png",
  },
  {
    id: 3,
    title: "Career Growth in Tech",
    type: "Seminar",
    date: "06 Jun",
    time: "2:00 PM",
    location: "Auditorium",
    attendees: 98,
    image: "/images/friend/event1.png",
  },
  {
    id: 4,
    title: "Design Thinking Meetup",
    type: "Meetup",
    date: "14 Jun",
    time: "11:00 AM",
    location: "Lounge Area",
    attendees: 75,
    image: "/images/friend/event1.png",
  },
];