export const PROJECTS = [
  {
    id: 1,
    title: "AI Chatbot Assistant",
    category: "AI",
    tech: ["Python", "FastAPI", "React"],
    author: "John Doe",
    stars: "2.1k",
    forks: 300,
    image: "/images/friend/project1.png",
  },
  {
    id: 2,
    title: "E-commerce Web App",
    category: "Web",
    tech: ["React", "Node", "MongoDB"],
    author: "Priya Sharma",
    stars: "1.8k",
    forks: 245,
    image: "/images/friend/project1.png",
  },
  {
    id: 3,
    title: "Mobile Fitness Tracker",
    category: "Mobile",
    tech: ["Flutter", "Firebase"],
    author: "Rohit Singh",
    stars: "950",
    forks: 121,
    image: "/images/friend/project1.png",
  },
  {
    id: 4,
    title: "Movie Recommendation System",
    category: "ML",
    tech: ["Python", "ML", "Streamlit"],
    author: "Neha Patel",
    stars: "3.2k",
    forks: 512,
    image: "/images/friend/project1.png",
  },
  {
    id: 5,
    title: "Real-time Chat App",
    category: "Backend",
    tech: ["Node.js", "Socket.io"],
    author: "Karan Mehta",
    stars: "870",
    forks: 98,
    image: "/images/friend/project1.png",
  },
];