export const ADMIN_MARKET_TRANSACTIONS = [
  {
    id: 1,
    buyer: "rahul_25",
    buyerName: "Rahul Sharma",
    seller: "priya_notes",
    sellerName: "Priya Desai",
    product: "DBMS Complete Notes",
    amount: "₹199",
    date: "May 18, 2025",
    time: "10:24 AM",
    status: "Completed",
  },

  {
    id: 2,
    buyer: "ananya_cse",
    buyerName: "Ananya Singh",
    seller: "study_with_aman",
    sellerName: "Aman Verma",
    product: "Operating Systems Notes",
    amount: "₹149",
    date: "May 18, 2025",
    time: "09:15 AM",
    status: "Completed",
  },

  {
    id: 3,
    buyer: "dev_1704",
    buyerName: "Dev Patel",
    seller: "topper_ishita",
    sellerName: "Ishita Roy",
    product: "Data Structures Notes",
    amount: "₹249",
    date: "May 17, 2025",
    time: "07:40 PM",
    status: "Completed",
  },

  {
    id: 4,
    buyer: "mehuljain",
    buyerName: "Mehul Jain",
    seller: "priya_notes",
    sellerName: "Priya Desai",
    product: "Computer Networks Notes",
    amount: "₹179",
    date: "May 17, 2025",
    time: "05:30 PM",
    status: "Completed",
  },

  {
    id: 5,
    buyer: "sneha_21",
    buyerName: "Sneha Reddy",
    seller: "study_with_aman",
    sellerName: "Aman Verma",
    product: "Discrete Math Notes",
    amount: "₹129",
    date: "May 17, 2025",
    time: "03:20 PM",
    status: "Completed",
  },
];