export const ADMIN_LIBRARY_BOOKS = [
  {
    id: 1,
    title: "Database Management Systems",
    author: "IIT Bombay",
    subject: "DBMS",
    semester: "Sem 4",
    type: "Textbook",
    pages: 524,
    language: "English",
    rating: 4.8,
    reviews: 256,
    price: 320,
  },

  {
    id: 2,
    title: "Operating Systems Concepts",
    author: "IIT Delhi",
    subject: "OS",
    semester: "Sem 3",
    type: "Textbook",
    pages: 612,
    language: "English",
    rating: 4.6,
    reviews: 198,
    price: 350,
  },

  {
    id: 3,
    title: "Data Structures & Algorithms",
    author: "IIT Madras",
    subject: "DSA",
    semester: "Sem 3",
    type: "Reference",
    pages: 680,
    language: "English",
    rating: 4.7,
    reviews: 312,
    price: 380,
  },

  {
    id: 4,
    title: "Computer Networks",
    author: "IIT Kharagpur",
    subject: "CN",
    semester: "Sem 4",
    type: "Textbook",
    pages: 560,
    language: "English",
    rating: 4.5,
    reviews: 172,
    price: 310,
  },
];